AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend for the Serverless Task Tracker application

Globals:
  Function:
    Timeout: 10
    Runtime: python3.13 # Change this to python3.13 if that's what you used
    MemorySize: 128
    Environment:
      Variables:
        TASKS_TABLE: !Ref TasksTable

Resources:
  # The DynamoDB Table
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: tasks
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # The REST API Gateway
  TaskTrackerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # IAM Role for Lambda Functions
  TaskTrackerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: TaskTrackerDynamoDBPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource: !GetAtt TasksTable.Arn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # Lambda Functions
  GetTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/get_tasks/
      Handler: app.lambda_handler
      Role: !GetAtt TaskTrackerLambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tasks
            Method: GET
            RestApiId: !Ref TaskTrackerApi

  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/create_task/
      Handler: app.lambda_handler
      Role: !GetAtt TaskTrackerLambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tasks
            Method: POST
            RestApiId: !Ref TaskTrackerApi

  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/update_task/
      Handler: app.lambda_handler
      Role: !GetAtt TaskTrackerLambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: PUT
            RestApiId: !Ref TaskTrackerApi

  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/delete_task/
      Handler: app.lambda_handler
      Role: !GetAtt TaskTrackerLambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: DELETE
            RestApiId: !Ref TaskTrackerApi